### ISSUE TITLE
Imputation comparison allow passing multiple classifiers

### ISSUE THREAD

**Issue by Matgrb** [ing-bank/probatus#104]
**Problem Description**
Currently the ImputationSelector allows for testing multiple imputation strategies for a given classifier passed as `clf`. However, the user might want to repeat the test for multiple classifiers. In this case the entire ImputationSelector needs to be refit, for every model separately. The problem is, some of the imputation techniques are really time consuming, e.g. KNN Imputer. In such case, for each classifier we need to reimpute the dataset. If we allowed passing multiple models as clf, you could perform the imputation once only, and then test multiple models on it.

**Desired Outcome**
I suppose the user should be able to pass a dictionary as clf. This way, we can perform the imputation once on the entire dataset, and simply fit multiple models on it.
Then the plots would show different strategies for every model.

**Solution Outline**
Example clf input would be:
```
clf = {
    'XGBoost' : xgb.XGBoostClassifier(),
    'RF' : RandomForestClassifier(),
    'LR'  : LogisticRegression()
    }
```

This change requires modifications in the `ImputationSelector`, updating the docstrings, adding a unit tests, and updating the tutorial notebook with an example.

**Comment by ReinierKoops** [comment]
Imputation functionality was dropped due other libraries having more expansive functionality like feature engine and sklearn. Thus this issue can be closed.
