### ISSUE TITLE
Refactor TreeBucketer

### ISSUE THREAD

**Issue by timvink** [ing-bank/probatus#121]
Currently we have:

https://github.com/ing-bank/probatus/blob/2a71061e4662316619bd1e731c7c5094e7b707bb/probatus/binning/binning.py#L388-L418

However we could refactor using 

```python
from sklearn.tree import _tree
splits = np.unique(tree.tree_.threshold[tree.tree_.feature != _tree.TREE_UNDEFINED])
```

Which would mean we can remove all of `probatus/utils/tree.py`.

Let me know and I'll open a PR.

**Comment by Matgrb** [comment]
I think that is a good idea! Feel free to make a PR.
