### ISSUE TITLE
Low Variance Feature Eliminator

### ISSUE THREAD

**Issue by warriordrago** [ing-bank/probatus#122]
**Problem Description**
Prior to running feature elimination it is a good idea to remove features which do not meet Quality Assurance criteria. One of them is features with very low variance (<0.00001). Typically those features are almost static and almost have no signal.

**Desired Outcome**
Write a class with fit/transform/plot methods which would eliminate features with low variance. Basically it is a wrapper for sklearn's VarianceThreshold class.

**Solution Outline**
Below is starting code:

```python
class VarianceThresholdSelector(BaseEstimator, TransformerMixin):
    """
    A Selector class based on sklearn's VarianceThreshold class.

    We want to drop columns with a variance equal to or below
    the given threshold but keep the pandas framework.

    This class is designed to fit with sklearn's Pipeline framework, for example:

    pipe = Pipeline([('selector', VarianceThresholdSelector(threshold=0.0)),
                     ('lr', LogisticRegression())])
    pipe.fit(X, y)
    """

    def __init__(self, threshold=0.0):
        """Initialise the Selector.

        Any column with variance equal to or below the threshold will be thrown away.

        Args:
            threshold: the variance threshold for sklearn's
                       VarianceThreshold class
        """
        self.threshold = threshold
        self.selector = VarianceThreshold(threshold)

    def fit(self, X, y=None):
        """Fit the VarianceThreshold classs from scikit learn.

        The additional factor here is we store the columns that are above the variance threshold.

        Args:
             X: the feature labels.
             y: None to satisfy the sklearn Pipeline framework
        """
        self.selector.fit(X)
        self.columns_above_threshold = X.columns[self.selector.get_support(indices=True)]
        self.columns_dropped = set(X.columns) - set(self.columns_above_threshold)
        return self

    def transform(self, X, y=None):
        """Transform a pandas DataFrame using the stored columns from the fit() function.

        Args:
            X: the feature labels
            y: None to satisfy the sklearn Pipeline framework

        Returns:
            X with columns that were above the variance threshold
        """
        X = X.copy()
        return X[self.columns_above_threshold]
```

**Comment by Matgrb** [comment]
I think overall this would be a good fit, however, now I looked into the code that is already available in sklearn it covers most of the functionality.

As I see the `VarianceThreshold` has the fit_transform interface, but also has arguments `variances_` and `threshold` so one can easily retrieve columns removed and kept. I am afraid that adding it to probatus would add too little value, given that this is already available in sklearn, and amount of work needed to implement it consistently with probatus API and standards (docs+tests+tutorials).

Do you see any other benefit for implementing this wrapper?

**Comment by warriordrago** [comment]
Actually, now looking at the original code of sklearn, this just adds feature names which were dropped in a list, and thats about it. So not much added value given the amount of extra work which needs to be done to add it to probatus. 

The only additional thing I can think of: If you have both categorical and continues features, one threshold for all wont work, even if the continuous data is normalised. One way could be to expand the `VarianceThreshold ` and use normal approximation to estimate the variance of the categorical data as n*p*(1-p), where p is the fraction of 1's in the feature. Or I can look up some other ways.

**Comment by Matgrb** [comment]
Let's keep it out of `probatus` for now, because impact/effort ratio is low for this feature. 

I will close this issue for now. If you have further ideas, feel free to reopen it.
