### ISSUE TITLE
Make a contribution checklist

### ISSUE THREAD

**Issue by Matgrb** [ing-bank/probatus#123]
Right now contributing file presents overview of different parts of the project to consider when contributing.

However, in case a new feature is added, there are many different parts that need to be modified:
- unit tests,
- example code in docstring
- unit tests for docstring code
- mkdocs tutorial
- ...

Same applies when someone wants to edit existing feature

The idea would be to make "Feature contribution checklist" and "New feature implementation checklist" that we can share, whenever anyone wants to pick up implementing PRs.

**Comment by timvink** [comment]
Good example: https://scikit-learn.org/stable/developers/contributing.html

**Comment by timlod** [comment]
Should code style be part of the contribution checklist, or do you run formatting in some pipeline?
As an aside, you mention that you use `black`, but I'm not sure what line_length (and others) setting you use - I wasn't able to recreate the exact formatting with black on my end.

**Comment by Matgrb** [comment]
We use `pre-commit` hook https://github.com/ing-bank/probatus/blob/main/.pre-commit-config.yaml. This file describes all standards.

Contributing file mentions that you need to install pre-commit first.

**Comment by timlod** [comment]
Ah great, I missed that, thanks!
