### ISSUE TITLE
"The passed model is not callable and cannot be analyzed directly with the given masker"

### ISSUE THREAD

**Issue by komodovaran** [ing-bank/probatus#127]
**Issue Description**

Following the tutorial, I would expect to be able to pass an unfitted GridSearchCV object into the eliminator. However, I'm scratching my head as to what the error means.

I've tried with both imblearn and sklearn pipelines, and get the same error.

```
imba_pipeline = make_pipeline(
    RobustScaler(),
    SMOTE(k_neighbors=3, sampling_strategy="minority"),
    RandomForestClassifier(max_features="sqrt"),
)

kf = StratifiedKFold(n_splits=3)

gs_params = {
    "randomforestclassifier__n_estimators": [10, 20, 30],
    "randomforestclassifier__max_depth": [2, 4, 6, 10, 12, 20],
    "randomforestclassifier__min_samples_split": [2, 3],
}

clf = GridSearchCV(
    imba_pipeline,
    param_grid=gs_params,
    cv=kf,
    scoring="recall",
    n_jobs=cpu_count(),
)

shap_elimination = ShapRFECV(
    clf=clf.best_estimator_, step=0.2, cv=3, scoring="recall", n_jobs=cpu_count()
)
report = shap_elimination.fit_compute(X_train, y_train)

final_features_set = shap_elimination.get_reduced_features_set(num_features=5)
```

**Comment by Matgrb** [comment]
Hi, thanks for openning an issue on this.

I tried to reproduce your error and I see 2 issues here:
1. When you pass to `clf` to `ShapRFECV`, you need to pass `clf` and not `clf.best_estimator_`
```
shap_elimination = ShapRFECV(
    clf=clf, step=0.2, cv=3, scoring="recall", n_jobs=cpu_count()
)
```

2. We use SHAP to calculate feature importance. Currently we only pass the model to the SHAP explainer and extract the feature importance. However, if you pass the model pipeline, SHAP cannot handle that.

I suggest to for now apply the preprocessing and oversampling before passing the data to ShapRFECV, and there only use RandomSearchCV.
In the future, we need to add the support for model pipelines #128 , by simply extracting the last step of the pipeline, before passing it to SHAP. 

Let me know if it helps.

**Comment by Matgrb** [comment]
Did this solution work? I close this issue now, feel free to reopen in case the solution fails.
