### ISSUE TITLE
Why is this library loading Tensorflow?

### ISSUE THREAD

**Issue by komodovaran** [ing-bank/probatus#135]
Loading the base `shap` library does not trigger TensorFlow unless absolutely necessary for model explanation. E.g., I can use the TreeExplainer just fine without touching TensorFlow.

However, the single statement `from probatus import ShapRFECV` somehow triggers a TensorFlow import. Normally, this wouldn't be an issue, but in this case it triggers a mysterious malloc memory error (even though I can still train a typical neural network without issues!).

I know most of the fault probably lies with TensorFlow. An interesting phenomenon nonetheless.

This happened in a Conda environment with TensorFlow 2.1, probatus 1.7.0 and shap 0.39.

_Yes, I will box in TensorFlow in a separate environment from now on._

**Comment by timvink** [comment]
Indeed, while not stated explicitly as a dependency,  `shap` can load `tensorflow` (see https://github.com/slundberg/shap/search?q=tensorflow)

Some of these imports are not inside functions, like this one:

https://github.com/slundberg/shap/blob/9411b68e8057a6c6f3621765b89b24d82bee13d4/shap/models/_topk_lm.py#L13-L16

`probatus` uses `import shap` in three places:

https://github.com/ing-bank/probatus/blob/1c61ba3c55cf64ae1f2cf1a3b570ff36073ca2f5/probatus/interpret/model_interpret.py#L32

https://github.com/ing-bank/probatus/blob/6f5d5e58a508d6e8b66b6a766717325441972436/probatus/utils/shap_helpers.py#L21

https://github.com/ing-bank/probatus/blob/1c61ba3c55cf64ae1f2cf1a3b570ff36073ca2f5/probatus/sample_similarity/resemblance_model.py#L33

That could explain why tensorflow is loaded. The solution might be to be more explicit with namespace we're importing from shap, so `from shap import`. That's good practice anyway.

**Comment by Matgrb** [comment]
Fix will be released in 1.8.2, thanks @eduardo-lourenco for contribution
