### ISSUE TITLE
Broken init arguments table in Missing Imputation Selector

### ISSUE THREAD

**Issue by Matgrb** [ing-bank/probatus#141]
**Describe the bug**
Broken init arguments table in Missing Imputation Selector
https://ing-bank.github.io/probatus/api/imputation_selector.html

One needs to check the docstring of init, and make sure running `mkdocs serve` provides correct API table

**Comment by Matgrb** [comment]
@anilkumarpanda Can you have a look at this one? it is probably something very small

**Comment by anilkumarpanda** [comment]
Seems like,will have a look.
