### ISSUE TITLE
Compatibility issue with matplotlib

### ISSUE THREAD

**Issue by priyanshj** [ing-bank/probatus#155]
Package is facing compatibility issue with matplotlib (v3.1.0) and importing ShapRFECV is throwing an error.

`ValueError: variadic keyword parameters cannot have default values`

**Comment by timvink** [comment]
Hi @priyanshj 

Can you try using the latest version of matplotlib ? `v3.1.0` is almost 2 years old, the latest version is `v.3.4.3`. You can upgrade using `pip install --upgrade matplotlib`

If that doesn't solve it.. what version of python are you on? (`python -V`) and what version of probatus (`pip list | grep probatus`)?

**Comment by ReinierKoops** [comment]
@priyanshj is this still an issue? Otherwise will close it.

**Comment by ReinierKoops** [comment]
Please feel free to make another issue when this is encountered again. I believe it should be fixed in the latest version.
