### ISSUE TITLE
EarlyStoppingShapRFECV with LightGBM - Error after all categorical features have been removed

### ISSUE THREAD

**Issue by lproth** [ing-bank/probatus#170]
The following error occurs once all categorical features have been removed:

AttributeError: 'TreeEnsemble' object has no attribute 'values'

This is due to a known issue with SHAP and LightGBM (https://github.com/slundberg/shap/issues/480). Check on line 98 of shap_helpers.py usually deals with this issue by calling SHAP explainer differently when categoricals are present. However when all categorical features have been dropped the error still presents itself. Quick solution is to set a flag in the beginning if any categorical features are present and then use that flag instead of the check on line 98. Would be good to understand why this happens though.

**Environment:**

 - probatus 1.8.5
 - Shap 0.38.1
 - LightGBM 3.2.1 
 - python 3.8.2
 - OS: linux

**To Reproduce**

```python
from probatus import feature_elimination
from sklearn.model_selection import StratifiedKFold
import lightgbm as lgb
import pandas as pd

X = pd.DataFrame(
    [
        [1,2,3,4,5,101,102,103,104,105],
        [-1,-2,2,-5,-7,1,2,5,-1,3],
        ["a", "b"] * 5, # noisy categorical will dropped first
    ]
).transpose()
X[2] = X[2].astype("category")
X[1] = X[1].astype("float")
X[0] = X[0].astype("float")
y = [0] * 5 + [1] * 5

model = lgb.LGBMClassifier()

n_iter = 2

n_folds = 3

for i in range(n_iter):
    skf = StratifiedKFold(n_folds, shuffle=True, random_state=42)
    shap_elimination = feature_elimination.EarlyStoppingShapRFECV(
        clf=model,
        step=1 / (n_iter + 1),
        cv=skf,
        scoring="accuracy",
        eval_metric="logloss",
        early_stopping_rounds=5,
    )
    report = shap_elimination.fit_compute(
        X,
        y,
    )
```

**Error traceback**

If applicable please provide full traceback of the error.

```
Traceback (most recent call last):
  File "/home/luke/.virtualenvs/af/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 431, in _process_worker
    r = call_item()
  File "/home/luke/.virtualenvs/af/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 285, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/luke/.virtualenvs/af/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/home/luke/.virtualenvs/af/lib/python3.8/site-packages/joblib/parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "/home/luke/.virtualenvs/af/lib/python3.8/site-packages/joblib/parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "/home/luke/.virtualenvs/af/lib/python3.8/site-packages/probatus/feature_elimination/feature_elimination.py", line 1079, in _get_feature_shap_values_per_fold
    shap_values = shap_calc(
  File "/home/luke/.virtualenvs/af/lib/python3.8/site-packages/probatus/utils/shap_helpers.py", line 108, in shap_calc
    explainer = Explainer(model, masker=mask, **shap_kwargs)
  File "/home/luke/.virtualenvs/af/lib/python3.8/site-packages/shap/explainers/_explainer.py", line 161, in __init__
    explainers.Tree.__init__(self, self.model, self.masker, link=self.link, feature_names=self.feature_names, **kwargs)
  File "/home/luke/.virtualenvs/af/lib/python3.8/site-packages/shap/explainers/_tree.py", line 177, in __init__
    self.expected_value = self.model.predict(self.data).mean(0)
  File "/home/luke/.virtualenvs/af/lib/python3.8/site-packages/shap/explainers/_tree.py", line 1091, in predict
    tree_limit = self.values.shape[0]
AttributeError: 'TreeEnsemble' object has no attribute 'values'
```

**Expected behavior**

Should run fine even once all categorical features are dropped.

**Comment by Matgrb** [comment]
Thanks for making the issue, i have managed to reproduce it, i also managed to fix it, by simply setting the column names in X to string like:
```
["1", "2", "3"]
```
I think shap for some reason does not handle well dataframes with int as column names, same as index values.

In order to mitigate the issue, one needs to modify `probatus/utils/arrayfuncs/assure_pandas_df` function to check if the passed X as any of the following DF, Series, list of lists, np.array, ends up as pandas DF, with **column names as strings**. It would be also good to make a small unit test for that function the case when someone passes DF with int column names, and to check whether they get transformed to strings.

Who would like to pick that up? That would be an important addition to the package :)

**Comment by lproth** [comment]
That doesn't fix it for me. The below dataframe still gives the error:

`X = pd.DataFrame(
    {
        "num1": [1,2,3,4,5] + [101,102,103,104,105],
        "num2": [-1,-2,2,-5,-7] + [1,2,5,-1,3],
        "cat": ["a", "b"] * 5, # noisy so dropped first
    }
)

X["cat"] = X["cat"].astype("category")
X["num1"] = X["num1"].astype("float")
X["num2"] = X["num2"].astype("float")

y = [0] * 5 + [1] * 5
`

**Comment by ClaudioSalvatoreArcidiacono** [comment]
I was trying to investigate this issue today and it seems more serious that what I thought. Given our tests setup:

```python
def complex_data():
    """
    Fixture.
    """

    feature_names = ["f1_categorical", "f2_missing", "f3_static", "f4", "f5"]

    # Prepare two samples
    X, y = make_classification(
        n_samples=50,
        class_sep=0.05,
        n_informative=2,
        n_features=5,
        random_state=0,
        n_redundant=2,
        n_clusters_per_class=1,
    )
    X = pd.DataFrame(X, columns=feature_names)
    X["f1_categorical"] = X["f1_categorical"].astype("category")
    X.loc[0:10, "f2_missing"] = np.nan
    return X, y
```

The following test passes:
```python
    from lightgbm import LGBMClassifier

    model = LGBMClassifier(n_estimators=50, max_depth=3, num_leaves=3)
    shap_elimination = EarlyStoppingShapRFECV(
        clf=model,
        step=0.33,
        cv=10,
        scoring="accuracy",
        eval_metric="logloss",
        early_stopping_rounds=5,
    )
    X, y = complex_data()

    report = shap_elimination.fit_compute(
        X,
        y,
    )
```

but changing the `cv` value to `5` fails with the error

```
AttributeError: 'TreeEnsemble' object has no attribute 'values'
```
I have tried the following things without success: 

- dropping the categorical feature
- adding the shap_kwarg `feature_perturbation="tree_path_dependent"` as suggested in the issue of shap

I still did not figure out when this issue happen and why.
