### ISSUE TITLE
Masking based on columns not rows

### ISSUE THREAD

**Issue by gverbock** [ing-bank/probatus#176]
When looking at the `utils/shap_helpers.py` I see that a mask is defined. However, if I am right, the mask is defined on the number col columns while it should be the number of row.

![image](https://user-images.githubusercontent.com/32060943/145012439-1777c1eb-b9b2-462d-984c-60734da568df.png)

I would propose the followoing change

```
X.shape[1]
```

Would become 

```
X.shape[0]
```

Also:

There is a typo in model_interpret.py on row 99.

![image](https://user-images.githubusercontent.com/32060943/144943676-9067583c-1435-499f-969e-7a6db53a9037.png)

Should be **neither**

**Comment by gverbock** [comment]
@Matgrb @timvink I saw I messed-up the pipeline (sorry about that). What is the best option? Revert the previous merge and re-open this issue or create a new issue?

**Comment by Matgrb** [comment]
No worries Gilles!
If you would like to fix the pipeline and test the fix, you can make a PR that implements it and see if tests succeed :)
