### ISSUE TITLE
Implement automatic feature selection methods (Finish work started by #173)

### ISSUE THREAD

**Issue by markdregan** [ing-bank/probatus#219]
This feature request proposes to finish the proposal from #173 

**Problem Description**
Many ML workflows require some form of automatic decision making when it comes to the number of features selected by probatus RFECV. Currently, probatus requires the user to specify the number of features selected. If a user could inspect RFECV stats from probatus for each iteration, they would identify the optimum iteration by trading off things like model score (eg. AUC), standard deviation of the score, number of features selected etc. I propose a few simply automatic feature selection strategies.

**Desired Outcome**
Expand `get_reduced_features_set()` by allowing user to specify each of 
- `num_features = "best"`
- `num_features = "best_coherent"`
- `num_features = "best_parsimonious"`

**Definitions:**
- **best:** strictly selects the num_features with the highest model score
- **best_coherent:** For iterations that are within one standard error (this can be a parameter) of the highest score, select the iteration with the lowest standard deviation of model score
- **best_parsimonious:** For iterations that are within one standard error of the highest score, select the iteration with the fewest features

**Additional params**
- **standard_error_threshold:** Default value of 1. Only applies when num_features == "best*"

**Solution Outline**
- Suggest building on `get_reduced_features_set()` to return list of feature names.

**Open questions:**
- Do we need to support `_ranking` and `_support`? If so, I suggest this is computed on demand - because it is dependent on which automatic feature selection technique is used. One option, is to have another parameter within `get_reduced_features_set()` called `return_type` which takes values of ["feature_names", "support", "ranking"]. `feature_names` would be the default.

**Comment by ReinierKoops** [comment]
Awesome, to answer your question I’d opt for the “another parameter option” since we want to support ranking & support, if that’s computed on demand that would be ok.

**Comment by ReinierKoops** [comment]
Awesome work @markdregan !
