### ISSUE TITLE
Antivirus blacklisted and blocked Probatus website

### ISSUE THREAD

**Issue by GegznaV** [ing-bank/probatus#227]
When I try opening [ing-bank.github.io/probatus](https://ing-bank.github.io/probatus) website, my antivirus blocks it as a blacklisted website (`URL:Blacklist`):

![image](https://github.com/ing-bank/probatus/assets/12725868/a00d7353-e9ca-4113-95a0-7c6fb9ba0e32)

Why is the website blacklisted?

**Comment by ReinierKoops** [comment]
It’s believed this is due to outdated mkdocs.

**Comment by GegznaV** [comment]
How this issue should be solved. It is not possible to access the documentation of the package.

**Comment by ReinierKoops** [comment]
Updating mkdocs package since the website is build using an outdated version of it. Some of its code is deprecated

**Comment by GegznaV** [comment]
Should this be solved on the user's or developer's side?

**Comment by ReinierKoops** [comment]
The new PR should maybe fix the issue for you.

**Comment by ReinierKoops** [comment]
Is this still an issue? if it is it would be a issue on your pc.

**Comment by GegznaV** [comment]
Hi, thank you. Now I can open the website. So now we can close #277
