### ISSUE TITLE
Spark Support of ShapRFECV

### ISSUE THREAD

**Issue by avinashbarnwal** [ing-bank/probatus#231]
**Problem Description**
We would like to have Spark Support for the package

**Desired Outcome**
Spark DataFrame as input

**Solution Outline**
Replace Pandas Dataframe with Spark DataFrame as input

**Comment by ReinierKoops** [comment]
Please feel free to start/try making an implementation for it

**Comment by ReinierKoops** [comment]
Will look into it if we can provide an notebook where ShapRFECV is used as part of PySpark pipeline. I think I have an example somewhere on my other laptop.

**Comment by ReinierKoops** [comment]
As it currently stands, we use the SHAP package. This package at the moment only supports pandas. If they start supporting more packages way of saving data (pyspark, polars, ...) then we will also be able to make our package compatible with that and by doing so allow for Spark Dataframe as input. 

Right now the only thing we can do is have some kind of wrapper that allows us to run pandas+shap code on pyspark without converting it to spark dataframe. 

Also we could try and allow other dataframe types like pyspark in this package but for now that would result in immediate conversion when we call the SHAP library which will be inefficient.

**Comment by avinashbarnwal** [comment]
Thanks for the comment. We can close it.
