### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'bool'.

### ISSUE THREAD

**Issue by realJPIrwin** [ing-bank/probatus#236]
**Issue Description**

Using numpy 1.24.4. Running ShapRFECV, appears to complete all training rounds successfully, then returns error: 

> AttributeError: module 'numpy' has no attribute 'bool'.
> `np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
> The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:

Do I need to downgrade or upgrade numpy? Which version is probatus configured for?

**Comment by ReinierKoops** [comment]
Numpy version 1.23.2

**Comment by ReinierKoops** [comment]
@realJPIrwin Is it working for you?

**Comment by ReinierKoops** [comment]
Please feel free to make another issue when this is encountered again. I believe it should be fixed in the latest version.
