### ISSUE TITLE
Create a new tag

### ISSUE THREAD

**Issue by erfanian7** [ing-bank/probatus#258]
**Issue Description**

Could you please create a new tag that includes the changes made in the following commit?

https://github.com/ing-bank/probatus/commit/75a0ab00b57b57f33008f2b2b11e706fe72b50eb

(I need  "shap>=0.43.0 ; python_version != '3.8'")
thank you

**Comment by ReinierKoops** [comment]
Hi @erfanian7 sorry for the delay and thanks for your interest! I've been waiting for my last PR's to be approved, so I could release 3.1.0. However this took longer than anticipated given that the refactoring was quite big. So I've released 3.0.1 (https://github.com/ing-bank/probatus/releases) in the mean time for you and maybe others that are waiting for it. I hope the other two PRs that are still open will be closed within the next two weeks meaning we'd release a version 3.1.0 as well.

**Comment by erfanian7** [comment]
I appreciate your help. The issue has been resolved.
