### ISSUE TITLE
Add references to stats tests methods

### ISSUE THREAD

**Issue by Matgrb** [ing-bank/probatus#28]
One of the functionality in probatus allows to perform the statistical tests on two samples of data:
  - `'ES'`: Epps-Singleton,
  - `'KS'`: Kolmogorov-Smirnov statistic,
  - `'PSI'`: Population Stability Index,
  - `'SW'`: Shapiro-Wilk based difference statistic,
  - `'AD'`: Anderson-Darling TS.

In multiple files we mention these tests in the docstrings, however, there are no references to the page/paper describing these tests. the references need to be added in:
- probatus.stats_tests.distribution_statistics.py both DistributionStatistic class and AutoDist class
- files in probatus.stats_tests: ad.py. es.py, ks.py, psi.py, sw.py
- docs.tutorials.nb_distribution_statistics.ipynb

Make sure that reference is added correctly as in MD file format. They should appear in the docs as a hyperlinks.

**Comment by dattanibedita** [comment]
Hello, may I work on this issue? Please let me know if the correct way to add a hyperlink to MD file format is the following:

[Text to be displayed](link to the website)

**Comment by Matgrb** [comment]
Hi! Great to hear you want to pick it up.

I suppose that this is the correct format. You can test if it works by first pip installing the following:

```
mkdocs-material>=6.1.0
mkdocs-git-revision-date-localized-plugin>=0.7.2
mkdocs-git-authors-plugin>=0.3.2
mkdocs-table-reader-plugin>=0.4.1
mkdocs-enumerate-headings-plugin>=0.4.3
mkdocs-awesome-pages-plugin>=2.4.0
mkdocs-minify-plugin>=0.3.0
mknotebooks>=0.6.2
mkdocs-print-site-plugin>=0.8.2
mkdocs-markdownextradata-plugin>=0.1.9
```
(these will be added to requirements.txt at some point in the future)

And then running `mkdocs serve` command in the to simulate how the probatus docs website will look like. It will show you an ip that you can open in a browser. On that website, you can check if the hyperlinks show up in the correct places e.g. API page for distribution statistics. 

In order to check which exactly test is used you can check the code in files probatus.stats_tests: ad.py. es.py, ks.py, psi.py, sw.py, which method was used.

**Comment by Matgrb** [comment]
@dattanibedita How is it going with implementation of this issue? Do you need some help?

In case you are stuck, feel free to make a PR, and I can have a look and give you some tips in the comments.

**Comment by dattanibedita** [comment]
Hello, I will open a PR soon. Where will I find the page/paper links that need to be mentioned in the docstring?

**Comment by adri0** [comment]
Completed by #158
