### ISSUE TITLE
Move tutorials to colab and add it to readme and mkdocs page

### ISSUE THREAD

**Issue by Matgrb** [ing-bank/probatus#30]
Make Colab notebooks, from existing tutorial notebooks and expose them in README table.

See example here:
https://github.com/ing-bank/popmon

TODO
- Make colab notebooks
- Add links in a table in readme
- Remove tutorial notebooks and replace them with colab notebooks reference

**Comment by timvink** [comment]
Now part of the docs, closed in #56
