### ISSUE TITLE
Add codecov badge to README

### ISSUE THREAD

**Issue by Matgrb** [ing-bank/probatus#33]
The current code coverage badge in README points to gitlab, we want it to use the coverage report from github

**Comment by timvink** [comment]
Currently I don't have enough permissions to add build secrets to the repo settings. Ping me when it's fixed :)

**Comment by timvink** [comment]
Done!

![image](https://user-images.githubusercontent.com/5570380/104334311-79f74880-54f2-11eb-8658-a9e82a3e846e.png)
