### ISSUE TITLE
Use cross references in the API documentation

### ISSUE THREAD

**Issue by timvink** [ing-bank/probatus#40]
You can provide relative links to module using [cross references](https://pawamoy.github.io/mkdocstrings/usage/#cross-references)

It makes it easy to link modules like the ones mentioned in this intro:

![image](https://user-images.githubusercontent.com/5570380/100367940-3bb9ce80-3003-11eb-966a-f9b66406906d.png)
https://ing-bank.github.io/probatus/api/sample_similarity.html

**Comment by adri0** [comment]
This has been resolved in #158
