### ISSUE TITLE
ShapRFECV implement features to keep parameter

### ISSUE THREAD

**Issue by Matgrb** [ing-bank/probatus#50]
**Desired Outcome**
Shap RFECV makes it possible to remove from features to prune a set of features to keep always

**Solution Outline**
The fit method has a parameter features to keep, at each step, the method will make sure to not remove the features to always keep.

**Comment by anilkumarpanda** [comment]
Looks, like a good enhancement. Will work on this one.

**Comment by timvink** [comment]
Any suggestion for the API yet? Probably makes sense to put this in [`.fit()`](https://ing-bank.github.io/probatus/api/feature_elimination.html#probatus.feature_elimination.feature_elimination.ShapRFECV.fit
), but that one already has a parameter 'column_names'. Maybe `columns_to_keep` ?

That said, adding extra parameters makes usage more complicated, even if it's a simple parameter. Do you see if as a parameter a large percentage of users would use? Why not add the columns back after calling `.get_reduced_features_set()` ?

**Comment by Matgrb** [comment]
The name `columns_to_keep` is a good suggestion. I agree with slightly harder usage, but also more advanced functionality could be useful in the package. 

@timvink Some of the `columns_to_keep` might have predictive power that will cause different features removed in the backwards elimination process, compared to just removing these features at the beginning and adding them back later. It would be better to allow the model optimize with these features, and at each iteration eliminate lowest importance feature that is not within `columns_to_keep`.

Some points to consider before implementing:
1. `min_features_to_select ` parameter now has to be higher or equal to the length `columns_to_keep`. Since `min_features_to_select ` is passed at object init, and `columns_to_keep` would be passed in fit, since this is when the data is passed as well, you need to throw exception in case the numbers don't match. You also have to ensure that the `columns_to_keep` all the columns are in the provided df.

2.  when `step` is a float, it is going to remove % of features left at a given iteration. In iteration  with `step=0.5`if you have 50 features left and 10 columns to keep, do we remove 25 features or 20 features? 

3. The stopping criterion for the rfecv iterations changes e.g. case you want to remove 4 features at this iteration, and you have 5 features left and 2 that you want to keep. Are there any edge cases here?

**Comment by anilkumarpanda** [comment]
W.r.t to API interface,I had the same thing in mind. cols_to_keep parameter in the fit function. With some validation checks.

With the initial tests, the approach of adding the features to keep in each iteration creates an infinite loop. Eg. if we want to keep one feature and the same feature is removed in that iteration and we add it after the iteration the process is stuck in a loop. I will test a this a bit more.

A simpler approach of removing cols_to_keep in the beginning and adding them in the `.get_reduced_features_set()` function should work.

**Comment by Matgrb** [comment]
I think it is best to just modify the function `_get_current_features_to_remove `, remove features to keep at the beginning. What do you think?

**Comment by timvink** [comment]
> Some points to consider before implementing: 1) min_features_to_select parameter now has to be higher or equal to the length columns_to_keep. Since min_features_to_select is passed at object init, and columns_to_keep would be passed in fit, since this is when the data is passed as well, you need to throw exception in case the numbers don't match. You also have to ensure that the columns_to_keep all the columns are in the provided df.

I think we can avoid trowing exceptions at users by updating the documentation, f.e.

-  `step` is the number of features to remove. If `cols_to_keep` is specified, it is the number of features to remove after keeping those columns.
- `min_features_to_select` is minimum number of features to be kept. This is a stopping criterion of the feature elimination. By default the process stops when one feature is left.  If `cols_to_keep` is specified, it is the number of features to remove after keeping those columns, which means `min_features_to_select` can also be set to zero.

**Comment by Matgrb** [comment]
`step` is be the number of features to remove at each iteration. But if it is a float then it is a percentage of features that are left (annealing). Either way, good docstring and trying to add as simple logic as possible to the code should be good.

I agree that it is better to not throw the exception with `min_features_to_select `. Maybe a warning when `verbose>50`?
