### ISSUE TITLE
ShapRFECV accept sequence / range to `step` parameter

### ISSUE THREAD

**Issue by timvink** [ing-bank/probatus#52]
**Problem Description**

Currently `ShapRFECV` parameter `step` only accepts an `int` or a `float`:

https://github.com/ing-bank/probatus/blob/ed5ab8cff256d03955fefe200d5d1ae24634b68f/probatus/feature_elimination/feature_elimination.py#L95-L100

**Desired Outcome**

For long running models, I would like to be able to control the number of features selected more precisely.

**Solution Outline**

 By providing a list of the # features selected in each step, you would allow more control. For example:

```python
shap_elimination = ShapRFECV(clf=search, step=[20,17,15], cv=10, scoring='roc_auc')

# or
shap_elimination = ShapRFECV(clf=search, step=list(range(100,70,-4)) + list(range(70,50,-2)) + list(range(50,10,-1)), cv=10, scoring='roc_auc', n_jobs=3)
```

**Comment by Matgrb** [comment]
It is a good idea! The user would be able to have more control over how many features are removed in each iteration.

We would need to document it well for the users, because this option is not available in sklearn RFECV, and to make sure all the checks of the input are in place.

**Comment by Matgrb** [comment]
Now looking at this, I think this will increase complexity of the parameter quite a bit. I suppose for now the option of using float as `step` parameter provides a lot of power to speed up the process in the beginning. 

Plus, @operte currently works on EarlyStoppingShapRFECV, which will be super fast compared to ShapRFECV. It will not require any optimization and will only apply early stopping in XGBoost and LGBM, which will be the fastest option for ShapRFECV.

For now, I will close this issue, and in case we see we need more flexibility for `step` parameter, we can reopen it.
