### ISSUE TITLE
SHAPImportanceResemblance.__init__ has no source code on API documentation

### ISSUE THREAD

**Issue by operte** [ing-bank/probatus#55]
**Problem Description**
The API Documentation of `SHAPImportanceResemblance` is not showing the source of the `__init__` method.

**Desired Outcome**
For consistency, it would be good to show the `__init__` source code on the API Documentation.

**Solution Outline**
All other methods already show their corresponding  `__init__` source codes. I assume that the API Documentation is automatically generated, so there must be an option that's keeping this particular one out of the documentation.

**Comment by Matgrb** [comment]
I agree :) this should be relatively easy fix, most probably in mkdocs.yml. You can test if the solution works by building the docs using:
```
mkdocs build
```

Feel free to pick it up :)

**Comment by timvink** [comment]
Is fixed with the latest release. See https://ing-bank.github.io/probatus/api/sample_similarity.html#probatus.sample_similarity.resemblance_model.SHAPImportanceResemblance
