### ISSUE TITLE
Desired Outcome

### ISSUE THREAD

**Issue by JCCKwong** [ing-bank/probatus#59]
**Desired Outcome**
ShapModelInterpreter to support model_ouput="probability" from SHAP TreeExplainer.

Thanks for a fantastic library.

**Comment by Matgrb** [comment]
It is currently supported. The fit() function has keyword argument called `**shap_kwargs`, which indicates that you can pass keyword arguments to the TreeExplainer. 

```
feature_importance = shap_interpreter.fit_compute(X_train, X_test, y_train, y_test, model_ouput="probability")
```

You can do this for any argument in TreeExplainer, the only constraint is that you need to explicitly name it in the same way.
