### ISSUE TITLE
requirements.yml file is missing

### ISSUE THREAD

**Issue by anilkumarpanda** [ing-bank/probatus#62]
requirements.yml file is missing.

**Comment by Matgrb** [comment]
small correction: requirements.txt

Currently the requirements are described in setup.py in setup_requires section. These are the "must" have libraries to run probatus code. Indeed having a requirements.txt file would be useful for developers, e.g. we could place there the requirements for using mkdocs and pytest. Keep in mind there is currently requirements_test.txt file in tests/ folder.

I would say either we move the requirements.txt to the root, and add the mkdocs requirements, or we keep it as it is. What do you think?

**Comment by timvink** [comment]
For packages I recommend defining all requirements 'sets' in `setup.py`. Sets would be: documentation, tests, development, core, and all. You define these sets via `install_requires` and `extras_require`.

You can then install what you need via `pip install probatus[name-of-set]`.

For an example setup see https://github.com/koaning/scikit-lego/blob/master/setup.py

If we go this way, we should also update CONTRIBUTING.md and the different github action pipelines.

**Comment by anilkumarpanda** [comment]
Sounds like a good idea. I will create a new issue for this and link this discussion there.
