### ISSUE TITLE
Update the setup.py file to include requirement sets

### ISSUE THREAD

**Issue by anilkumarpanda** [ing-bank/probatus#65]
**Problem Description**
As of now, there is no requirement.txt , inorder to make it easier for the developers to contribute to we can define sets in the setup.py file.

**Desired Outcome**
The setup.py file is updated to include sets.
We should also update CONTRIBUTING.md and the different github action pipelines.

**Solution Outline**
Sets would be: documentation, tests, development, core, and all. E.g [setup](https://github.com/koaning/scikit-lego/blob/master/setup.py) 
Define these sets via install_requires and extras_require.
You can then install what you need via pip install probatus[name-of-set].

Refer [this issue](https://github.com/ing-bank/probatus/issues/62) for the detailed discussion.

**Comment by Matgrb** [comment]
We should add the extra requirements for setting up the mkdocs documention:
```
mkdocs-material>=6.1.0
mkdocs-git-revision-date-localized-plugin>=0.7.2
mkdocs-git-authors-plugin>=0.3.2
mkdocs-table-reader-plugin>=0.4.1
mkdocs-enumerate-headings-plugin>=0.4.3
mkdocs-awesome-pages-plugin>=2.4.0
mkdocs-minify-plugin>=0.3.0
mknotebooks>=0.6.2
mkdocs-print-site-plugin>=0.8.2
mkdocs-markdownextradata-plugin>=0.1.9
```

**Comment by timvink** [comment]
Picking this up now
