### ISSUE TITLE
Install probatus in colab notebooks

### ISSUE THREAD

**Issue by Matgrb** [ing-bank/probatus#67]
Colab notebooks in documentation tutorials do not have the probatus installed.

One needs to install it in the environment in each notebook

**Comment by Matgrb** [comment]
@timvink if you have some time can you have a look at this one?

**Comment by timvink** [comment]
Solution is to add `!pip install probatus` block. Some dependencies are not in the base requirements of probatus, so I solved #65 first, so we can do `pip install 'probatus[all]'`. I added `%%capture` magic to ensure output does not display in our docs. Will submit PR shortly.
