### ISSUE TITLE
Failed auto docs deployment during release

### ISSUE THREAD

**Issue by Matgrb** [ing-bank/probatus#84]
After this change #58 github has a workflow that updates the mkdocs website at each release.

Currently, when i tried to make a release the workflow fails:
https://github.com/ing-bank/probatus/runs/2003842919?check_suite_focus=true

This might be caused by the fact that github requires passing username and password before pushing to the gh-pages branch.

**Comment by timvink** [comment]
Fix in 9da4871fafa60cba2a7205f7274c06d90a431d3b , probably. Let's see next release.
