### ISSUE TITLE
ShapRFECV - get_reduced_features_set 

### ISSUE THREAD

**Issue by hende8** [ing-bank/probatus#87]
Hi,
**Problem Description**
When I use **get_reduced_features_set** function I have to send "num_features". So my question is if I can get an ideal num_features in advance? 
I want to get number of features and then to use **get_reduced_features_set** function.
Thanks! 

**Desired Outcome**
I want to get number of features and then to use **get_reduced_features_set** function.

**Comment by timvink** [comment]
Hi @hende8 ! In my opinion, an ideal `num_features` does not exist. Use less features, you'll have a simpler model, use more features you'll have slightly higher performance (hopefully also on `test` and in actual production). This balance is a business decision, one to discuss with stakeholders. Another factor might be how much work is it to maintain and monitor a model with a lot of features.

That said, a good place to start is using `probatus`'s plot feature. From the [blogpost introduction ShapRFECV](https://medium.com/ing-blog/open-sourcing-shaprfecv-improved-feature-selection-powered-by-shap-994fe7861560):

![image](https://user-images.githubusercontent.com/5570380/110020232-a036a900-7d29-11eb-84a2-d14afd1fcc2b.png)

From that plot, you might decide your ideal number of features is somewhere between 3-8. Pick a number & then consider doing a much larger search on hyperparameters to squeeze the last bit of performance out of your model.

Does this help? Or did you have something more specific in mind?

**Comment by Matgrb** [comment]
The same discussion is covered in #31 . I agree with @timvink that in each case the user should select what is optimal for the problem that is being solved. 

However, for consistency with sklearn RFECV, as well as usability, we can implement a method that returns the single best feature set (as requested by @hende8 ), accourding to Validation AUC mean and std. We could also add a warning for a user, that this is an estimate, and it needs to be taken with caution.

What do you think?
