### ISSUE TITLE
Roadmap: Upcoming features

### ISSUE THREAD

**Issue by Matgrb** [ing-bank/probatus#93]
This issue is used to keep track of the of upcoming features that might be implemented in the future:
- [ ] Correlated features elimination routine [#9](https://github.com/ing-bank/probatus/issues/9)
- [ ]  Data shift detection [#72](https://github.com/ing-bank/probatus/issues/72)

This list will be updated in case new ideas are proposed and approved in the Issues tab of probatus.

**Comment by anilkumarpanda** [comment]
We also have the 
Features to keep update in SHAPRFECV #50

**Comment by Matgrb** [comment]
This issue is created to keep track of the future features.
The issues closed in each release are covered in CHANGELOG, the specific one is released in 1.6.0.

**Comment by ReinierKoops** [comment]
Closing this as I believe the issues mentioned need to be re-evaluated with regards to the order of importance. Please feel free to add your comments here #209
