### ISSUE TITLE
Setup dependabot for probatus

### ISSUE THREAD

**Issue by timvink** [ing-bank/probatus#96]
This project depends on quite some large projects. That brings a risk that any update on those packages might break probatus. We could fix versions, but that will probably force users into using out of date package.

The solution is to use dependabot. We fix dependencies to the latest version, and dependabot will submit a PR everytime a package has an update. That PR triggers github actions to re-run the unit tests, and if they succeed we can merge, if they don't, we're at least aware and can fix quickly. Downside is we will have to manually create minor releases for these updated dependencies, but we can automate that later as well.

**Comment by Matgrb** [comment]
I agree this would be a great change for the project.

Especially if we could select, which of the dependencies are critical, and for those we would have to merge by hand. I suppose SHAP would be one of them. For others we could decide, how much they can break, and possibly merge them automatically if tests don't fail.

**Comment by timvink** [comment]
FYI, in the end we did not implement dependabot. Lots of issues around getting a set of compatible packages together, better to let `pip` figure that one out.
